TARGET_DATARMNET_ENABLE := false

ifeq ($(TARGET_KERNEL_DLKM_DISABLE), true)
	ifeq ($(TARGET_KERNEL_DLKM_DATARMNET_OVERRIDE), true)
		TARGET_DATARMNET_ENABLE := true
	endif
else
	TARGET_DATARMNET_ENABLE := true
endif

ifeq ($(TARGET_DATARMNET_ENABLE), true)
	#Build rmnet core
	DATA_DLKM_BOARD_PLATFORMS_LIST := lahaina
	DATA_DLKM_BOARD_PLATFORMS_LIST += taro
	DATA_DLKM_BOARD_PLATFORMS_LIST += sa2150p
	DATA_DLKM_BOARD_PLATFORMS_LIST += kalama
	DATA_DLKM_BOARD_PLATFORMS_LIST += bengal
	DATA_DLKM_BOARD_PLATFORMS_LIST += monaco
	DATA_DLKM_BOARD_PLATFORMS_LIST += crow
	DATA_DLKM_BOARD_PLATFORMS_LIST += trinket

	ifneq ($(TARGET_BOARD_AUTO),true)
		ifneq ( ,$(call is-board-platform-in-list2,$(DATA_DLKM_BOARD_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_core.ko
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_ctl.ko
		endif
	endif
endif
